/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MU_FOOD_COURTS;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;


/**
 *
 * @author Rabel
 */
public class MU_FOOD_COURTS extends javax.swing.JFrame {

    double [] i = new double[10];
    double FinalMeal = 0.0, DrinkTotal, VCost = 1.50;
    double firstnumber;
    double secondnumber;
    double result;
    String operations;
    /**
     * Creates new form MU_FOOD_COURTS
     */
    public MU_FOOD_COURTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        subTotalTextBox = new javax.swing.JTextField();
        jlblVAT = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCConverter = new javax.swing.JComboBox<>();
        jTextConvert = new javax.swing.JTextField();
        jCurrency = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblCostOfDrinks = new javax.swing.JTextField();
        jlblCostOfMeal = new javax.swing.JTextField();
        jlblCostOfParcel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jBtnplus = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtnMulti = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnEqual = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jCKolizi = new javax.swing.JCheckBox();
        jSamosa = new javax.swing.JCheckBox();
        jSandwich = new javax.swing.JCheckBox();
        jTextKolizi = new javax.swing.JTextField();
        jTextSamosa = new javax.swing.JTextField();
        jTextSandwich = new javax.swing.JTextField();
        jCmbDrink = new javax.swing.JComboBox<>();
        jCVat = new javax.swing.JCheckBox();
        jCParcel = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        subTotalTextBox.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        subTotalTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        subTotalTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalTextBoxActionPerformed(evt);
            }
        });

        jlblVAT.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jlblVAT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jlblVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblVATActionPerformed(evt);
            }
        });

        jlblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jlblTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel4.setText("Subtotal:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel5.setText("VAT:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel6.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblVAT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subTotalTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jCConverter.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jCConverter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Dollar", "Pound", "Rupee" }));
        jCConverter.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 204)));
        jCConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCConverterActionPerformed(evt);
            }
        });

        jTextConvert.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jTextConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTextConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextConvertActionPerformed(evt);
            }
        });

        jCurrency.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jCurrency.setForeground(new java.awt.Color(0, 102, 102));
        jCurrency.setText("    Currency Converter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextConvert)
                    .addComponent(jCConverter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jCConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jlblCostOfDrinks.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jlblCostOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jlblCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostOfDrinksActionPerformed(evt);
            }
        });

        jlblCostOfMeal.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jlblCostOfMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jlblCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostOfMealActionPerformed(evt);
            }
        });

        jlblCostOfParcel.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jlblCostOfParcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jlblCostOfParcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostOfParcelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel1.setText("Cost of Drinks");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel2.setText("Cost of Meal");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel3.setText("Cost of Parcel");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostOfMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfParcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfParcel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N

        jPanel13.setBackground(new java.awt.Color(204, 153, 0));

        jTextArea1.setBackground(new java.awt.Color(204, 153, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Receipt", jPanel13);

        jPanel12.setBackground(new java.awt.Color(204, 153, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jPanel12.setToolTipText("");

        jtxtDisplay.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));

        jBtn1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnCancel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnCancel.setText("C");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jBtnplus.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnplus.setText("+");
        jBtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnplusActionPerformed(evt);
            }
        });

        jBtnMinus.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });

        jBtnMulti.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnMulti.setText("*");
        jBtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiActionPerformed(evt);
            }
        });

        jBtnDivide.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });

        jBtnDot.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnDot.setText(".");
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });

        jBtnEqual.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtnEqual.setText("=");
        jBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("       A Project Of AK47");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jBtn8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                                .addComponent(jBtn5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(jBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBtnMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnMinus)
                                    .addComponent(jBtnplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDivide)
                    .addComponent(jBtnMulti)
                    .addComponent(jBtnMinus))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn7)
                            .addComponent(jBtn8)
                            .addComponent(jBtn9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn4)
                            .addComponent(jBtn5)
                            .addComponent(jBtn6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn1)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jBtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnDot)
                        .addComponent(jBtnEqual))
                    .addComponent(jBtn0))
                .addGap(38, 38, 38)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel12);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 153, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jCKolizi.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jCKolizi.setText("Kolizi Shingara");
        jCKolizi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCKoliziMouseClicked(evt);
            }
        });

        jSamosa.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jSamosa.setText("Samosa");
        jSamosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSamosaMouseClicked(evt);
            }
        });
        jSamosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSamosaActionPerformed(evt);
            }
        });

        jSandwich.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jSandwich.setText("Sandwich");
        jSandwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSandwichMouseClicked(evt);
            }
        });
        jSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSandwichActionPerformed(evt);
            }
        });

        jTextKolizi.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jTextKolizi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTextKolizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKoliziActionPerformed(evt);
            }
        });

        jTextSamosa.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jTextSamosa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTextSamosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSamosaActionPerformed(evt);
            }
        });

        jTextSandwich.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jTextSandwich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jCmbDrink.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jCmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink", "Water", "Tea", "Coffee", "Coca-Cola", "Sprite", "Mango Juice", " ", " " }));
        jCmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDrinkActionPerformed(evt);
            }
        });

        jCVat.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jCVat.setText("VAT");
        jCVat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCVatMouseClicked(evt);
            }
        });

        jCParcel.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jCParcel.setText("Parcel ");
        jCParcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCParcelMouseClicked(evt);
            }
        });
        jCParcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCParcelActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel9.setText(" Drinks");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCVat)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCmbDrink, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCParcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCKolizi)
                            .addComponent(jSandwich)
                            .addComponent(jSamosa))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSamosa)
                            .addComponent(jTextSandwich)
                            .addComponent(jTextKolizi))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jCKolizi)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSamosa)
                            .addComponent(jTextSamosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextKolizi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSandwich)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCVat)
                    .addComponent(jCParcel))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(204, 153, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jBtnTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jBtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotalMouseClicked(evt);
            }
        });
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jBtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReceiptMouseClicked(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jBtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnResetMouseClicked(evt);
            }
        });
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReset)
                    .addComponent(jBtnExit))
                .addContainerGap())
        );

        jLabel7.setBackground(new java.awt.Color(204, 153, 0));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 38)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 0));
        jLabel7.setText(" MU FOOD COURT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextKoliziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKoliziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKoliziActionPerformed

    private void jSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSandwichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSandwichActionPerformed

    private void jTextSamosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSamosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSamosaActionPerformed

    private void jCmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDrinkActionPerformed
    
        double Tea = 10, Water = 15, Coffee = 20;
        double Coca_Cola = 30, Sprite = 35, Mango_Juice = 50;
        if(jCmbDrink.getSelectedItem().equals("Select a drink"))
        {
            jlblCostOfDrinks.setText(null);
            FinalMeal += 0.0;
            DrinkTotal = 0.0;
        }
        
        if(jCmbDrink.getSelectedItem().equals("Water"))
        {
            FinalMeal += Water;
            DrinkTotal = Water;
            
            String cWater = String.format(" %.2f",Water);
            jlblCostOfDrinks.setText(cWater);
        }
        
        if(jCmbDrink.getSelectedItem().equals("Tea"))
        {
            FinalMeal += Tea;
            DrinkTotal = Tea;
            
            String cTea = String.format(" %.2f",Tea);
            jlblCostOfDrinks.setText(cTea);
        }
        
        if(jCmbDrink.getSelectedItem().equals("Coffee"))
        {
            FinalMeal += Coffee;
            DrinkTotal = Coffee;
            
            String cCoffee = String.format(" %.2f",Coffee);
            jlblCostOfDrinks.setText(cCoffee);
        }
        
        if(jCmbDrink.getSelectedItem().equals("Coca-Cola"))
        {
            FinalMeal += Coca_Cola;
            DrinkTotal = Coca_Cola;
            
            String cCoca_Cola = String.format(" %.2f",Coca_Cola);
            jlblCostOfDrinks.setText(cCoca_Cola);
        }
        
        if(jCmbDrink.getSelectedItem().equals("Sprite"))
        {
            FinalMeal += Sprite;
            DrinkTotal = Sprite;
            
            String cSprite = String.format(" %.2f",Sprite);
            jlblCostOfDrinks.setText(cSprite);
        }
        
        if(jCmbDrink.getSelectedItem().equals("Mango Juice"))
        {
            FinalMeal += Mango_Juice;
            DrinkTotal = Mango_Juice;
            
            String cMango_Juice = String.format(" %.2f",Mango_Juice);
            jlblCostOfDrinks.setText(cMango_Juice);
        }
    }//GEN-LAST:event_jCmbDrinkActionPerformed

    private void jCParcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCParcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCParcelActionPerformed

    private void jBtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnplusActionPerformed
        firstnumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jBtnplusActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
      String Enternumber = jtxtDisplay.getText()+ jBtn7.getText();
      jtxtDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        firstnumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
        firstnumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
       String Enternumber = jtxtDisplay.getText()+ jBtn8.getText();
      jtxtDisplay.setText(Enternumber); 
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
       String Enternumber = jtxtDisplay.getText()+ jBtn9.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText()+ jBtn4.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
       String Enternumber = jtxtDisplay.getText()+ jBtn5.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
       String Enternumber = jtxtDisplay.getText()+ jBtn6.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
       String Enternumber = jtxtDisplay.getText()+ jBtn1.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String Enternumber = jtxtDisplay.getText()+ jBtn2.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText()+ jBtn3.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText()+ jBtn0.getText();
      jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
       jtxtDisplay.setText(jtxtDisplay.getText() + jBtnDot.getText());
    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jBtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiActionPerformed
        firstnumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jBtnMultiActionPerformed

    private void jBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualActionPerformed
        String answer;
        secondnumber = Double.parseDouble(jtxtDisplay.getText());
        if(operations == "+")
        {
            result = firstnumber + secondnumber;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "-")
        {
            result = firstnumber - secondnumber;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "*")
        {
            result = firstnumber * secondnumber;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "/")
        {
            result = firstnumber / secondnumber;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jBtnEqualActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jCConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCConverterActionPerformed
        
        if(jCConverter.getSelectedItem().equals("Choose One..."))
        {
            jTextConvert.setText(null);
        }
        /*
        Dollar
        Pound
        Rupee
        */
        if(jCConverter.getSelectedItem().equals("Dollar"))
        {
            //double test = 500;
            double cTotal1 = Double.parseDouble(jlblTotal.getText());
            //double cTotal2 = Double.parseDouble(jlblCostOfMeal.getText());
            //double cTotal3 = Double.parseDouble(jlblCostOfParcel.getText());
        //jBtnTotal
            String Dol = String.format(" $%.2f",cTotal1/80);
            jTextConvert.setText(Dol);
        }
        
        if(jCConverter.getSelectedItem().equals("Rupee"))
        {
            double cTotal2 = Double.parseDouble(jlblTotal.getText());
            //double test = 500;
            String Dol = String.format(" R%.2f",cTotal2/1.50);
            jTextConvert.setText(Dol);
        }
        
        if(jCConverter.getSelectedItem().equals("Pound"))
        {
            double cTotal3 = Double.parseDouble(jlblTotal.getText());
            //double test = 500;
            String Dol = String.format(" £%.2f",cTotal3/129);
            jTextConvert.setText(Dol);
        }
    }//GEN-LAST:event_jCConverterActionPerformed

    private void jTextConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextConvertActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jlblCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostOfDrinksActionPerformed

    private void jlblCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostOfMealActionPerformed

    private void jlblCostOfParcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostOfParcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostOfParcelActionPerformed

    private void subTotalTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalTextBoxActionPerformed

    private void jlblVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblVATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblVATActionPerformed

    private void jlblTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTotalActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jCParcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCParcelMouseClicked
        
       double PCost = 5.00;
        
        if(jCParcel.isSelected())
        {
            String Deli = String.format(" %.2f",PCost);
            jlblCostOfParcel.setText(Deli);
        }
        else
        {
            jlblCostOfParcel.setText(null);
            //PCost = 0.0;
        }
    }//GEN-LAST:event_jCParcelMouseClicked

    private void jCVatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCVatMouseClicked

        if(jCVat.isSelected())
        {
            String Tax = String.format(" %.2f",VCost);
            jlblVAT.setText(Tax);
        }
        else
        {
            jlblVAT.setText(null);
            //VCost = 0.0;
        }
    }//GEN-LAST:event_jCVatMouseClicked

    private void jBtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnResetMouseClicked
        
        jlblVAT.setText(null);
        jlblCostOfParcel.setText(null);
        jlblCostOfDrinks.setText(null);
        subTotalTextBox.setText(null);
        jlblCostOfMeal.setText(null);
        jlblTotal.setText(null);
        jlblCostOfMeal.setText(null);
        jTextKolizi.setText(null);
        jlblCostOfMeal.setText(null);
        jTextSamosa.setText(null);
        jTextSandwich.setText(null);
        jlblCostOfMeal.setText(null);
        
        jCKolizi.setSelected(false);
        jSamosa.setSelected(false);
        jSandwich.setSelected(false);
        
        jCVat.setSelected(false);
        jCParcel.setSelected(false);
        
        subTotalTextBox.setText(null);
        jTextConvert.setText(null);
        jCmbDrink.setSelectedIndex(0);
        jCConverter.setSelectedIndex(0);
        jTextArea1.setText(null);
        FinalMeal = 0.0;
        i[0] = 0.0;i[1] = 0.0;i[1] = 0.0;i[2] = 0.0;
        DrinkTotal = 0.0;
        VCost = 1.50;
       // PCost = 5.00;
    }//GEN-LAST:event_jBtnResetMouseClicked

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jCKoliziMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCKoliziMouseClicked
        
        i[0] = 0.0;
       // double cMeal = 0.0;
        double Kolizi = Double.parseDouble(jTextKolizi.getText());
        
        double Ikolizi = 10.00;
        
        if(jCKolizi.isSelected())
        {
            i[0] = (Kolizi * Ikolizi) + FinalMeal;
            String pMeal = String.format(" %.2f",i[0]);
            jlblCostOfMeal.setText(pMeal);
            FinalMeal += i[0];
        }
        else
        {
            i[0] = 0.0;
            jlblCostOfMeal.setText(null);
            FinalMeal += 0.0;
        }
    }//GEN-LAST:event_jCKoliziMouseClicked

    private void jSamosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSamosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSamosaActionPerformed

    private void jSamosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSamosaMouseClicked
        
        i[1] = 0.0;
        //double cMeal = 0.0;
        double Samosa = Double.parseDouble(jTextSamosa.getText());
        
        double ISamosa = 8.00;
        
        if(jSamosa.isSelected())
        {
            i[1] = (Samosa * ISamosa) + FinalMeal;
            String pMeal = String.format(" %.2f",i[1]);
            jlblCostOfMeal.setText(pMeal);
            FinalMeal += i[1];
        }
        else
        {
            i[1] = 0.0;
            FinalMeal += 0.0;
            jlblCostOfMeal.setText(null);
        }
    }//GEN-LAST:event_jSamosaMouseClicked

    private void jSandwichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSandwichMouseClicked
        
        i[2] = 0.0;
        //double cMeal = 0.0;
        double Sandwich = Double.parseDouble(jTextSandwich.getText());
        
        double ISandwich = 20.00;
        
        if(jSandwich.isSelected())
        {
//            cMeal = Double.parseDouble(jlblCostOfMeal.getText());
            i[2] = (Sandwich * ISandwich) + FinalMeal;
            String pMeal = String.format(" %.2f",i[2]);
            jlblCostOfMeal.setText(pMeal);
            FinalMeal += i[2];
        }
        else
        {
            i[2] = 0.0;
            FinalMeal += 0.0;
            jlblCostOfMeal.setText(null);
        }
    }//GEN-LAST:event_jSandwichMouseClicked

    private void jBtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotalMouseClicked
        
//        double cTotal1 = Double.parseDouble(jlblCostOfDrinks.getText());
//        double cTotal2 = Double.parseDouble(jlblCostOfMeal.getText());
//        double cTotal3 = Double.parseDouble(jlblCostOfParcel.getText());
        
        double allTotal = (i[0] + i[1] + i[2])+ VCost + DrinkTotal;
        String iTotal = String.format(" %.2f",allTotal);
        jlblTotal.setText(iTotal);
        
        double sTotal = (i[0] + i[1] + i[2]) + DrinkTotal;
        String jTotal = String.format(" %.2f",sTotal);
        subTotalTextBox.setText(jTotal);
    }//GEN-LAST:event_jBtnTotalMouseClicked

    private void jBtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReceiptMouseClicked
        
//        double R1 = Double.parseDouble(jTextKolizi.getText());
//        double R2 = Double.parseDouble(jTextSamosa.getText());
//        double R3 = Double.parseDouble(jTextSandwich.getText());
        double R1 = 0.0, R2 = 0.0, R3 = 0.0;
       if(jCKolizi.isSelected())
        {
            R1 = 0.0 + Double.parseDouble(jTextKolizi.getText());
        }
        if(jSamosa.isSelected())
        {
            R2 = Double.parseDouble(jTextSamosa.getText());
        }
        if(jSandwich.isSelected())
        {
//        double R1 = Double.parseDouble(jTextKolizi.getText());
//        double R2 = Double.parseDouble(jTextSamosa.getText());
            R3 = Double.parseDouble(jTextSandwich.getText());
        }
        double To = i[0] + i[1] + i[2] + 1.50;
        jTextArea1.append("You are served by MU COURT\n\nKolizi Shingara:  " + 
                R1 + " Piece's\nSamusa:\t" + R2 + " Piece's\nSandwitch:\t" 
                + R3 + " Piece's\nTotal Paid:\t" + To +
                "/=\n\tA Project of AK47\n\n");
    }//GEN-LAST:event_jBtnReceiptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MU_FOOD_COURTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MU_FOOD_COURTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MU_FOOD_COURTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MU_FOOD_COURTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MU_FOOD_COURTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEqual;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMulti;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jBtnplus;
    private javax.swing.JComboBox<String> jCConverter;
    private javax.swing.JCheckBox jCKolizi;
    private javax.swing.JCheckBox jCParcel;
    private javax.swing.JCheckBox jCVat;
    private javax.swing.JComboBox<String> jCmbDrink;
    private javax.swing.JLabel jCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox jSamosa;
    private javax.swing.JCheckBox jSandwich;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextConvert;
    private javax.swing.JTextField jTextKolizi;
    private javax.swing.JTextField jTextSamosa;
    private javax.swing.JTextField jTextSandwich;
    private javax.swing.JTextField jlblCostOfDrinks;
    private javax.swing.JTextField jlblCostOfMeal;
    private javax.swing.JTextField jlblCostOfParcel;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jlblVAT;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField subTotalTextBox;
    // End of variables declaration//GEN-END:variables
}
